[build]
  command = "npm run build"  # Your build command
  publish = "build"          # Directory where your build files are stored

# Correct way to define environment variables in TOML:
  [build.environment]
    NODE_OPTIONS = "--openssl-legacy-provider"

